# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# NOTE: This workflow is intended to be used manually for example on fork
#       branches to validate that all Spot REST and websocket unit tests
#       run through successfully.
#
#       This is required in PR when changes were made that (could) affect
#       the Spot related code parts.
#
#       To run this action the following secrets must be set in the forked
#       repository:
#         * SPOT_API_KEY
#         * SPOT_SECRET_KEY
#
#       ... see the README for information about how to generate Spot API keys.
#       Please also make shure to enable the following API permissions:
#         * Query funds
#         * Deposit funds
#         * Query open orders & trades
#         * Query closed orders & trades
#         * Query ledger entries
#         * Export data
#         * Access WebSockets API
#
#       Disable all other permissions since we don't want to create or cancel
#       real orders or withdraw funds during testing. These tests are disabled
#       by default but having the permissions disabled is the safest way of
#       testing.
#

name: PR Manual Test Spot

on:
  workflow_dispatch:

jobs:
  Test-Spot-Public:
    uses: ./.github/workflows/_test_spot_public.yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  Test-Spot-Private:
    uses: ./.github/workflows/_test_spot_private.yaml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
