# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Workflow that gets triggered, when a release was created in the
# Github UI. This enables the upload of the python-kraken-sdk
# for the latest tag to PyPI.
#

name: PyPI Production Release

on:
  release:
    types: [created]

jobs:
  ##    Run pre-commit - just to make shure that the code is still
  ##    in the proper format
  ##
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yml

  ##    Build the package - for all Python versions
  ##
  Build:
    uses: ./.github/workflows/_build.yml
    needs: [Pre-Commit]
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  ##    Build the documentation
  ##
  Build-Doc:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build_doc.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.11"

  ##    Run all tests to validate the package
  ##
  Test:
    name: Test the package
    needs: [Build]
    uses: ./.github/workflows/_test.yml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  ##    Upload the python-kraken-sdk to PyPI
  ##
  UploadPyPI:
    needs: [Test]
    name: Upload the current release to PyPI
    uses: ./.github/workflows/_pypi_publish.yml
    with:
      REPOSITORY_URL: https://pypi.org/simple
    secrets:
      API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
