# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Workflow that gets triggered, when a release was created in the
# Github UI. This enables the upload of the python-kraken-sdk
# for the latest tag to PyPI.
#

name: PyPI Production Release

on:
  release:
    types: [created]

jobs:
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yml

  Build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  Test:
    name: Test the package
    needs: [Build]
    uses: ./.github/workflows/_test.yml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  UploadPyPI:
    needs: [Test]
    name: Upload the current release to PyPI
    uses: ./.github/workflows/_pypi_publish.yml
    with:
      API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      REPOSITORY_URL: https://pypi.org/simple
